server:
  port: 8080
  servlet:
    context-path: /e-market

spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: emarket
    password: emarket
    driver-class-name: oracle.jdbc.OracleDriver

security:
  jwt:
    secret: "jwt-market-e"
    expiration: 86400000 # 1 dia em milisegundos
  public:
    path: "/public/**"
