server:
  port: 8080
  servlet:
    context-path: /e-market

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
security:
  jwt:
    secret: "jwt-market-e"
    expiration: 86400000 # 1 dia em milisegundos
  public:
    path: "/public/**"
